
language: python
python:
  - 3.5
  - 3.6

cache:
  directories:
    - $TRAVIS_BUILD_DIR/.hypothesis

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - pip install -r requirements.txt
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install docutils==0.12
  - pip install coverage
  - pip install coveralls
  - pip install mypy
script:
  #Â Build the documentation
  - cd docs; make clean; make html
  # Run the test suit with coverage
  - cd ..
  - travis_wait 60 coverage run --source=axelrod -m unittest discover
  - coverage report -m
  # Run the doctests
  - python doctests.py
  # Run the type checker
  - python run_mypy.py
  # Check that all strategies are in the index
  - python run_strategy_indexer.py
after_success:
  - coveralls
notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/3cc093037c0df458209d

