
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script:
  #Â Build the documentation
  - cd docs; make html
  # Run the test suit with coverage
  - cd ..
  - coverage run --source=axelrod -m unittest discover
  - coverage report -m
  # Run the doctests
  #- sh doctest
  - python -m doctest docs/tutorials/getting_started/*rst
  - python -m doctest docs/tutorials/further_topics/*rst
  - python -m doctest docs/reference/*rst
  - python -m doctest docs/tutorials/contributing/strategy/*rst
  - python -m doctest docs/tutorials/advanced/strategy_transformers.rst
after_success:
  - coveralls
